### PR TITLE
update version rest-client

### PR DESCRIPTION
**Pull request by lvitals**
Rest-Client update to last version

### CODE REVIEW

**Comment by lvitals** [comment]
the latest version of rest-client does not support ruby ​​version 1.9.3

**Comment by lvitals** [comment]
this version of ruby ​​1.9 no longer has support, ended on February 23, 2015

**Comment by lvitals** [comment]
https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

**Comment by cmckni3** [comment]
Thanks!

**Pull request merged**
