### PR TITLE
be a little forgiving on the rails dependency

### PR DESCRIPTION
**Pull request by nicwillemse**
#9 Allowed rails 5 compatibility

### CODE REVIEW

**Comment by nicwillemse** [comment]
@cmckni3 could you look into this for me please ? Im unable to recreate this ?

**Comment by cmckni3** [comment]
@nicwillemse What is this PR trying to accomplish?

The tests on master should be good again. webmock 2.0 was released recently so I specified 1.24.x in the Gemfile.

**Comment by nicwillemse** [comment]
@cmckni3 i have simply updated the rails dependency ?

**Comment by cmckni3** [comment]
This change shouldn't have made a difference. I created a rails app with Rails 5 RC1 and can use the gem from within the app fine.

@nicwillemse Are you using any other gems with a strict Rails dependency?

I see you created some issues for `pdfjs_viewer-rails` (locked to Rails 4.2.x) and `grape_on_rails_routes` (locked to Rails >= 3.1.1 < 5). These gems will produce a bundler "unable to resolve dependencies" message. These gems will be included in the message as unresolvable and potentially other gems depending on Rails (depends on bundler version).

**Comment by cmckni3** [comment]
Ideally, I think I could get away with just depending on railties. I don't think I'm using anything from Rails itself but I would have to double check.

**Comment by nicwillemse** [comment]
Thanks for you help @cmckni3 im happy to make the change ?

**Comment by cmckni3** [comment]
Works for me. I added you as a collaborator.

Do you have other changes to make for this PR?

**Comment by nicwillemse** [comment]
@cmckni3 thanks for the add.

Im done with this PR, I tried switching it to railties but it seems there is a dependency on rails.

Perhaps we can remove this as a different PR and close this ? 

`oMethodError: undefined method `active_record' for #<Rails::Application::Configuration:0x007f905ae20350>
/Users/nic/Projects/rails-jasperserver/test/dummy/config/application.rb:50:in `<class:Application>'
/Users/nic/Projects/rails-jasperserver/test/dummy/config/application.rb:9:in `<module:Dummy>'
/Users/nic/Projects/rails-jasperserver/test/dummy/config/application.rb:8:in `<top (required)>'
/Users/nic/Projects/rails-jasperserver/test/dummy/Rakefile:5:in `require'
/Users/nic/Projects/rails-jasperserver/test/dummy/Rakefile:5:in `<top (required)>'
/Users/nic/Projects/rails-jasperserver/Rakefile:24:in `load'
/Users/nic/Projects/rails-jasperserver/Rakefile:24:in `<top (required)>'`

**Comment by cmckni3** [comment]
That makes sense because the the dummy application uses the Rails tasks. That can be fixed in a new PR.

**Pull request merged**
